# Generated by Django 4.2.5 on 2024-10-31 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_post_remove_provider_movie_remove_review_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
