# Generated by Django 4.2.5 on 2024-10-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(default='X', max_length=100),
            preserve_default=False,
        ),
    ]
